# Generated by Django 2.2.6 on 2020-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Game', 'Game'), ('Workout', 'Workout'), ('Meeting', 'Meeting'), ('Film', 'Film')], max_length=50)),
                ('time', models.DateTimeField(null=True)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
