# Generated by Django 2.2.6 on 2020-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0006_auto_20200108_1936'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(through='roster.Attendance', to='roster.Player'),
        ),
    ]
