# Generated by Django 2.2.6 on 2020-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present'), ('excused', 'Excused'), ('tardy', 'Tardy')], max_length=15),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=25),
        ),
    ]
