# Generated by Django 2.2.6 on 2020-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20200106_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=25),
        ),
    ]
