# Generated by Django 2.2.6 on 2020-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20200106_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
