# Generated by Django 2.2.6 on 2020-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_player_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
    ]
