# Generated by Django 2.2.6 on 2020-01-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('roster', '0005_remove_player_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='attendance_status',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present'), ('excused', 'Excused'), ('tardy', 'Tardy')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Player')),
            ],
        ),
    ]
