# Generated by Django 2.2.6 on 2020-01-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_auto_20200108_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present'), ('excused', 'Excused'), ('tardy', 'Tardy')], max_length=20),
        ),
    ]
