# Generated by Django 2.2.6 on 2020-01-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_player_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='attendance_status',
        ),
    ]
